[package]
name = "ls-pro"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.40", features = ["derive"] }
crossterm = "0.29.0"
chrono = "0.4"
lazy_static = "1.4.0"

[target.'cfg(unix)'.dependencies]
users = "0.11"